"""
curiosity_agent_v0_8.py
-----------------------
Developmental agent in a 20x20 structured environment.

This is a substantial extension of the v0.7.1 architecture. The changes:

ENVIRONMENT (20x20 grid with four cell types):
  - Frame cells: outer ring, impassable, perceptual signature "brown".
    Architectural analogue of the walls of a room.
  - Hazard cells: two interior clusters, impassable for v0.8,
    perceptual signature "red". Architectural analogue of the stove.
  - Attractor cells: six scattered interior cells, passable, perceptual
    signature "green-star". Entry delivers feature reward.
  - Neutral cells: the remaining interior cells. Passable. No signature.
    The medium of exploration.

AGENT (extends v0.7.1):
  - Perception extended: agent observes its current cell AND the cell
    types of the four adjacent cells. This supplies the information
    that primitive aversion and attraction operate on.
  - Primitive aversion: pre-learning Q-value penalty for actions that
    would lead into frame or hazard cells. The aversion is applied at
    action selection, not learned through experience.
  - Primitive attraction: small pre-learning Q-value bonus for actions
    leading toward attractor cells at one-step distance.
  - All drives from v0.7.1 preserved: novelty, learning progress,
    preference (accumulating progress + feature reward), feature drive.
  - Three-phase structure preserved: prescribed acquisition, integration,
    autonomy.

PHASE 1 PATH:
  A boustrophedon traversal of the 18x18 interior that routes AROUND
  hazard cells when they fall in the sweep path. Generated by a small
  path-planning function. The agent moves one adjacent step at a time;
  no teleportation.

PRE-REGISTERED METRICS:
  - Rule adherence: frame/hazard-directed action attempts by phase
  - Architectural generalisation: P3 concentration, feature ratio
  - Preference alignment: top-5 preferences on/near attractors
  - Coverage: passable cells visited during Phase 1

This version tests whether the architectural principles demonstrated
in the 10x10 world generalise to a structured, bounded, hazard-containing
larger environment.

Run from Terminal with:
    python3 curiosity_agent_v0_8.py
"""

import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict, deque, Counter

# --------------------------------------------------------------------------
# CONFIG
# --------------------------------------------------------------------------

GRID_SIZE = 20
NUM_STEPS = 20000  # scaled up from 10000 to accommodate larger world
PHASE_3_START_FRACTION = 0.6
Q_VALUE_RESET_MULTIPLIER = 0.3
FEATURE_DRIVE_WEIGHT = 0.15

# Cell type constants
FRAME = 0
NEUTRAL = 1
HAZARD = 2
ATTRACTOR = 3

# Primitive structures
AVERSION_PENALTY = -5.0      # large enough to dominate action selection
ATTRACTION_BONUS = 0.3       # small pull toward visible attractors

# Environment content: placed deterministically so batch runs are comparable
HAZARD_CLUSTERS = [
    [(5, 8), (5, 9), (6, 8)],    # cluster of 3 in lower-left interior
    [(14, 13), (14, 14)],         # cluster of 2 in upper-right interior
]
ATTRACTOR_CELLS = [
    (3, 3), (16, 3), (9, 10), (4, 15), (15, 16), (11, 5)
]
START_CELL = (1, 1)


# --------------------------------------------------------------------------
# ENVIRONMENT
# --------------------------------------------------------------------------

class StructuredGridWorld:
    """A 20x20 grid with frame, neutral, hazard, and attractor cells.

    The agent starts at START_CELL. It can move one cell at a time in
    four cardinal directions. Moves into frame or hazard cells are
    blocked: the agent remains where it was.
    """

    def __init__(self, size=GRID_SIZE):
        self.size = size
        self.agent_pos = START_CELL
        self._build_grid()

    def _build_grid(self):
        """Populate self.cell_type with the cell at each coordinate."""
        self.cell_type = {}
        self.hazard_cells = set()
        for cluster in HAZARD_CLUSTERS:
            for c in cluster:
                self.hazard_cells.add(c)
        self.attractor_cells = set(ATTRACTOR_CELLS)
        for x in range(self.size):
            for y in range(self.size):
                if x == 0 or x == self.size - 1 or y == 0 or y == self.size - 1:
                    self.cell_type[(x, y)] = FRAME
                elif (x, y) in self.hazard_cells:
                    self.cell_type[(x, y)] = HAZARD
                elif (x, y) in self.attractor_cells:
                    self.cell_type[(x, y)] = ATTRACTOR
                else:
                    self.cell_type[(x, y)] = NEUTRAL
        # Scope for the agent is all passable interior cells
        self.scope_cells = {
            c for c, t in self.cell_type.items()
            if t in (NEUTRAL, ATTRACTOR)
        }

    def is_passable(self, cell):
        t = self.cell_type.get(cell, FRAME)
        return t in (NEUTRAL, ATTRACTOR)

    def perceive_adjacent(self, cell):
        """Return the cell types of the four adjacent cells.

        Order: up, down, left, right. Out-of-grid counts as FRAME.
        """
        x, y = cell
        adj_coords = [(x, y - 1), (x, y + 1), (x - 1, y), (x + 1, y)]
        return tuple(self.cell_type.get(c, FRAME) for c in adj_coords)

    def observe(self):
        x, y = self.agent_pos
        ctype = self.cell_type[(x, y)]
        adj = self.perceive_adjacent(self.agent_pos)
        # State is (x, y, current_type, adj_up, adj_down, adj_left, adj_right)
        return (x, y, ctype, *adj)

    def step(self, action):
        """Attempt a move. Returns (observation, attempted_cell, success).

        action: 0=up, 1=down, 2=left, 3=right
        """
        x, y = self.agent_pos
        if action == 0:
            target = (x, y - 1)
        elif action == 1:
            target = (x, y + 1)
        elif action == 2:
            target = (x - 1, y)
        elif action == 3:
            target = (x + 1, y)
        else:
            target = self.agent_pos

        # Bounds check — treat out-of-grid as frame
        if not (0 <= target[0] < self.size and 0 <= target[1] < self.size):
            target_type = FRAME
        else:
            target_type = self.cell_type[target]

        if target_type in (FRAME, HAZARD):
            # Blocked. Agent stays put. Record the attempt.
            return self.observe(), target, False
        else:
            self.agent_pos = target
            return self.observe(), target, True


# --------------------------------------------------------------------------
# PATH PLANNING FOR PHASE 1
# --------------------------------------------------------------------------

def plan_phase_1_path(world, start=START_CELL):
    """Generate a traversal of all passable interior cells.

    Strategy: row-by-row sweep of the interior (y = 1 to 18), alternating
    left-to-right and right-to-left. When a hazard cell falls in the
    sweep, we detour one row and come back. Because hazards are sparse,
    the detour is short.

    Returns a list of (x, y) cells forming a connected path (each
    consecutive pair is adjacent), beginning at `start`.
    """
    size = world.size
    path = [start]
    visited = {start}

    # Rows 1..18 — sweep alternately
    for y in range(1, size - 1):
        row_cells_ltr = [(x, y) for x in range(1, size - 1)
                         if world.is_passable((x, y))]
        if y % 2 == 1:
            ordered = row_cells_ltr
        else:
            ordered = list(reversed(row_cells_ltr))

        for cell in ordered:
            if cell in visited:
                continue
            # Try to reach this cell from the current position of path[-1]
            # via a short walk through already-visited or adjacent passable
            # cells. For the sparse-hazard case this is usually one step.
            current = path[-1]
            if _is_adjacent(current, cell):
                path.append(cell)
                visited.add(cell)
            else:
                # Need to detour. Use a short BFS through passable cells.
                detour = _bfs_path(world, current, cell, visited)
                if detour is None:
                    # Skip this cell — unreachable given current path
                    continue
                for step_cell in detour[1:]:
                    path.append(step_cell)
                    visited.add(step_cell)

    return path


def _is_adjacent(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1


def _bfs_path(world, start, goal, already_visited):
    """Shortest path from start to goal through passable cells.

    already_visited cells are allowed as transit. Returns list of cells
    from start to goal inclusive, or None if no path.
    """
    from collections import deque as _deque
    queue = _deque([(start, [start])])
    seen = {start}
    while queue:
        node, path = queue.popleft()
        if node == goal:
            return path
        x, y = node
        for dx, dy in [(0, -1), (0, 1), (-1, 0), (1, 0)]:
            nxt = (x + dx, y + dy)
            if nxt in seen:
                continue
            if not world.is_passable(nxt):
                continue
            seen.add(nxt)
            queue.append((nxt, path + [nxt]))
    return None


def path_to_actions(path):
    """Convert a cell-path into a sequence of actions."""
    actions = []
    for i in range(len(path) - 1):
        a, b = path[i], path[i + 1]
        dx, dy = b[0] - a[0], b[1] - a[1]
        if dy == -1:
            actions.append(0)
        elif dy == 1:
            actions.append(1)
        elif dx == -1:
            actions.append(2)
        elif dx == 1:
            actions.append(3)
        else:
            actions.append(0)  # shouldn't happen
    return actions


# --------------------------------------------------------------------------
# AGENT
# --------------------------------------------------------------------------

class DevelopmentalAgent:
    def __init__(self, world, total_steps, num_actions=4):
        self.world = world
        self.scope = world.scope_cells
        self.total_steps = total_steps
        self.steps_taken = 0
        self.covered = set()
        self.num_actions = num_actions

        # Memory structures
        self.visit_counts = defaultdict(int)
        self.forward_model = defaultdict(lambda: defaultdict(int))
        self.fast_errors = defaultdict(lambda: deque(maxlen=5))
        self.slow_errors = defaultdict(lambda: deque(maxlen=30))
        self.cell_preference = defaultdict(float)
        self.q_values = defaultdict(float)

        # Phase tracking
        self.phase = 1
        self.phase_1_end_step = None
        self.phase_2_end_step = None
        self.phase_3_start_target = int(total_steps * PHASE_3_START_FRACTION)

        # Phase 1 prescribed path
        self.prescribed_path = plan_phase_1_path(world)
        self.prescribed_actions = path_to_actions(self.prescribed_path)
        self.path_index = 0

        # Learning parameters
        self.learning_rate = 0.1
        self.epsilon = 0.1

        # Rule-adherence tracking
        self.frame_attempts_by_phase = {1: 0, 2: 0, 3: 0}
        self.hazard_attempts_by_phase = {1: 0, 2: 0, 3: 0}

        self._apply_phase_weights()

    def _apply_phase_weights(self):
        if self.phase == 1:
            self.novelty_weight = 0.0
            self.progress_weight = 0.0
            self.preference_weight = 0.0
            self.feature_weight = 0.0
        elif self.phase == 2:
            self.novelty_weight = 0.3
            self.progress_weight = 1.2
            self.preference_weight = 0.0
            self.feature_weight = FEATURE_DRIVE_WEIGHT
        elif self.phase == 3:
            self.novelty_weight = 0.3
            self.progress_weight = 1.2
            self.preference_weight = 0.8
            self.feature_weight = FEATURE_DRIVE_WEIGHT

    def _transition_phase(self, new_phase):
        for key in list(self.q_values.keys()):
            self.q_values[key] *= Q_VALUE_RESET_MULTIPLIER
        self.phase = new_phase
        self._apply_phase_weights()

    def check_phase_transition(self):
        if self.phase == 1:
            if self.path_index >= len(self.prescribed_actions):
                self.phase_1_end_step = self.steps_taken
                self._transition_phase(2)
                return True
        elif self.phase == 2:
            if self.steps_taken >= self.phase_3_start_target:
                self.phase_2_end_step = self.steps_taken
                self._transition_phase(3)
                return True
        return False

    def get_prescribed_action(self):
        if self.path_index >= len(self.prescribed_actions):
            return None
        action = self.prescribed_actions[self.path_index]
        self.path_index += 1
        return action

    def _primitive_bias(self, state):
        """Compute Q-value biases from primitive aversion/attraction.

        State contains the current cell type and four adjacent cell types.
        Returns an array of four bias values, one per action.
        """
        # State layout: (x, y, current_type, adj_up, adj_down, adj_left, adj_right)
        adj_types = state[3:7]
        biases = np.zeros(4)
        for i, t in enumerate(adj_types):
            if t == FRAME or t == HAZARD:
                biases[i] = AVERSION_PENALTY
            elif t == ATTRACTOR:
                biases[i] = ATTRACTION_BONUS
        return biases

    def choose_action(self, state):
        """Drive-based action selection, used in Phase 2 and 3.

        Combines learned Q-values with primitive biases. Epsilon-greedy
        exploration.
        """
        if np.random.rand() < self.epsilon:
            # Even random exploration respects primitive aversion — we
            # exclude actions with strongly negative bias.
            biases = self._primitive_bias(state)
            valid = [a for a in range(self.num_actions) if biases[a] > AVERSION_PENALTY / 2]
            if not valid:
                valid = list(range(self.num_actions))
            return int(np.random.choice(valid))
        biases = self._primitive_bias(state)
        values = np.array([self.q_values[(state, a)] for a in range(self.num_actions)])
        combined = values + biases
        max_v = combined.max()
        best = [a for a in range(self.num_actions) if combined[a] == max_v]
        return int(np.random.choice(best))

    def novelty_reward(self, state):
        count = self.visit_counts[state]
        return self.novelty_weight / np.sqrt(count + 1)

    def preference_reward(self, state):
        if self.preference_weight == 0.0:
            return 0.0
        cell = (state[0], state[1])
        return self.preference_weight * self.cell_preference[cell]

    def feature_reward(self, state):
        """Reward for entering an attractor cell.

        State[2] is the current cell's type; ATTRACTOR = 3.
        """
        if self.feature_weight == 0.0:
            return 0.0
        return self.feature_weight * (1.0 if state[2] == ATTRACTOR else 0.0)

    def prediction_error(self, state, action, next_state):
        predictions = self.forward_model[(state, action)]
        total = sum(predictions.values())
        pseudo_vocab = 5
        smoothed_prob = (predictions[next_state] + 1) / (total + pseudo_vocab)
        return 1.0 - smoothed_prob

    def learning_progress(self, state, action):
        fast = self.fast_errors[(state, action)]
        slow = self.slow_errors[(state, action)]
        if len(fast) < 3 or len(slow) < 10:
            return 0.0
        fast_mean = np.mean(fast)
        slow_mean = np.mean(slow)
        progress = slow_mean - fast_mean
        return self.progress_weight * max(0.0, progress)

    def update_model(self, state, action, next_state, error, r_progress, r_feature):
        """Update forward model, error windows, visit counts, preferences.

        Preferences accumulate progress + feature reward (the v0.7.1 change).
        """
        self.visit_counts[next_state] += 1
        self.forward_model[(state, action)][next_state] += 1
        self.fast_errors[(state, action)].append(error)
        self.slow_errors[(state, action)].append(error)
        cell = (next_state[0], next_state[1])
        if cell in self.scope:
            self.covered.add(cell)
        self.cell_preference[cell] += r_progress + r_feature

    def update_values(self, state, action, next_state, intrinsic):
        if self.phase == 1:
            return
        future = max(self.q_values[(next_state, a)] for a in range(self.num_actions))
        td_target = intrinsic + 0.9 * future
        td_error = td_target - self.q_values[(state, action)]
        self.q_values[(state, action)] += self.learning_rate * td_error

    def record_action_attempt(self, target_cell, success, world):
        """Track whether the attempted action targeted a blocked cell.

        Only failures against FRAME or HAZARD count as attempts on those
        cell types. Success into a valid cell doesn't count.
        """
        if success:
            return
        # Action was blocked — find out what type of cell blocked it
        t = world.cell_type.get(target_cell, FRAME)
        if t == FRAME:
            self.frame_attempts_by_phase[self.phase] += 1
        elif t == HAZARD:
            self.hazard_attempts_by_phase[self.phase] += 1


# --------------------------------------------------------------------------
# RUN
# --------------------------------------------------------------------------

def run():
    world = StructuredGridWorld()
    agent = DevelopmentalAgent(world, NUM_STEPS)

    # Report environment
    print(f"Environment: {GRID_SIZE}x{GRID_SIZE}")
    print(f"  Frame cells     : {sum(1 for t in world.cell_type.values() if t == FRAME)}")
    print(f"  Hazard cells    : {len(world.hazard_cells)}")
    print(f"  Attractor cells : {len(world.attractor_cells)}")
    print(f"  Neutral cells   : {sum(1 for t in world.cell_type.values() if t == NEUTRAL)}")
    print(f"  Passable scope  : {len(world.scope_cells)}")
    print(f"  Phase 1 path    : {len(agent.prescribed_actions)} steps")
    print()

    heatmap_by_phase = {1: np.zeros((GRID_SIZE, GRID_SIZE)),
                        2: np.zeros((GRID_SIZE, GRID_SIZE)),
                        3: np.zeros((GRID_SIZE, GRID_SIZE))}
    coverage_pct_trace = []
    progress_trace = []
    novelty_trace = []
    preference_trace = []
    feature_trace = []
    mastered_count_trace = []

    state = world.observe()
    covered_at_phase_1_end = 0

    for step in range(NUM_STEPS):
        agent.steps_taken = step
        transitioned = agent.check_phase_transition()
        if transitioned and agent.phase == 2 and covered_at_phase_1_end == 0:
            covered_at_phase_1_end = len(agent.covered)

        if agent.phase == 1:
            action = agent.get_prescribed_action()
            if action is None:
                action = 0
        else:
            action = agent.choose_action(state)

        next_state, target_cell, success = world.step(action)
        agent.record_action_attempt(target_cell, success, world)

        error = agent.prediction_error(state, action, next_state)
        r_progress = agent.learning_progress(state, action)
        r_novelty = agent.novelty_reward(next_state)
        r_preference = agent.preference_reward(next_state)
        r_feature = agent.feature_reward(next_state)
        intrinsic = r_novelty + r_progress + r_preference + r_feature

        agent.update_model(state, action, next_state, error, r_progress, r_feature)
        agent.update_values(state, action, next_state, intrinsic)

        x, y = next_state[0], next_state[1]
        heatmap_by_phase[agent.phase][y, x] += 1

        coverage_pct_trace.append(100 * len(agent.covered) / len(agent.scope))
        progress_trace.append(r_progress)
        novelty_trace.append(r_novelty)
        preference_trace.append(r_preference)
        feature_trace.append(r_feature)
        mastered_count_trace.append(sum(
            1 for errs in agent.fast_errors.values()
            if len(errs) >= 5 and np.mean(errs) < 0.15
        ))
        state = next_state

    # --- ANALYSIS ---
    top_preferred = sorted(agent.cell_preference.items(),
                           key=lambda kv: -kv[1])[:5]

    def attractor_ratio(heatmap):
        total = heatmap.sum()
        if total == 0:
            return 0.0
        attractor_visits = sum(heatmap[y, x] for (x, y) in ATTRACTOR_CELLS)
        expected_share = len(ATTRACTOR_CELLS) / len(world.scope_cells)
        actual_share = attractor_visits / total
        return actual_share / expected_share if expected_share > 0 else 0.0

    def attention_cv(heatmap):
        visits = heatmap[heatmap > 0]
        if len(visits) < 2:
            return 0.0
        return visits.std() / visits.mean()

    p3_visits = heatmap_by_phase[3]
    p3_total = int(p3_visits.sum())
    if p3_total > 0:
        p3_concentration = p3_visits.max() / (p3_total / len(world.scope_cells))
    else:
        p3_concentration = 0.0

    # --- PLOTS ---
    fig, axes = plt.subplots(3, 2, figsize=(14, 14))

    def draw_heatmap(ax, heatmap, title, cmap):
        im = ax.imshow(heatmap, cmap=cmap, origin="upper")
        # Draw frame cells as dark overlay
        for (x, y), t in world.cell_type.items():
            if t == FRAME:
                ax.plot(x, y, marker="s", color="saddlebrown", markersize=3)
            elif t == HAZARD:
                ax.plot(x, y, marker="s", color="red", markersize=6)
            elif t == ATTRACTOR:
                ax.plot(x, y, marker="*", color="lime", markersize=12,
                        markeredgecolor="black", markeredgewidth=0.5)
        ax.set_title(title)
        plt.colorbar(im, ax=ax, fraction=0.046)
        ax.set_xlim(-0.5, GRID_SIZE - 0.5)
        ax.set_ylim(GRID_SIZE - 0.5, -0.5)

    draw_heatmap(axes[0, 0], heatmap_by_phase[1],
                 f"Phase 1 (Prescribed)\nended step {agent.phase_1_end_step}", "viridis")
    draw_heatmap(axes[0, 1], heatmap_by_phase[2],
                 f"Phase 2 (Integration)\n{agent.phase_2_end_step - agent.phase_1_end_step if agent.phase_2_end_step else 0} steps", "plasma")
    draw_heatmap(axes[1, 0], heatmap_by_phase[3],
                 f"Phase 3 (Autonomy)\n{NUM_STEPS - agent.phase_2_end_step if agent.phase_2_end_step else 0} steps", "magma")

    ax = axes[1, 1]
    ax.plot(coverage_pct_trace, linewidth=1.5, color="teal")
    if agent.phase_1_end_step:
        ax.axvline(agent.phase_1_end_step, color="orange", linestyle="--",
                   label=f"P1 end @ {agent.phase_1_end_step}")
    if agent.phase_2_end_step:
        ax.axvline(agent.phase_2_end_step, color="purple", linestyle="--",
                   label=f"P2 end @ {agent.phase_2_end_step}")
    ax.legend(loc="lower right", fontsize=8)
    ax.set_title("Coverage over time (% of passable scope)")
    ax.set_xlabel("Step"); ax.set_ylabel("% visited")
    ax.set_ylim(0, 105)

    ax = axes[2, 0]
    def running_mean(x, window=200):
        if len(x) < window:
            return np.array(x)
        c = np.cumsum(np.insert(x, 0, 0))
        return (c[window:] - c[:-window]) / window
    ax.plot(running_mean(progress_trace), linewidth=1.0, color="darkgreen", label="progress")
    ax.plot(running_mean(novelty_trace), linewidth=1.0, color="navy", label="novelty")
    ax.plot(running_mean(preference_trace), linewidth=1.0, color="crimson", label="preference")
    ax.plot(running_mean(feature_trace), linewidth=1.0, color="goldenrod", label="feature")
    if agent.phase_1_end_step:
        ax.axvline(agent.phase_1_end_step, color="orange", linestyle="--")
    if agent.phase_2_end_step:
        ax.axvline(agent.phase_2_end_step, color="purple", linestyle="--")
    ax.set_title("Drive signals over time (rolling mean)")
    ax.set_xlabel("Step"); ax.set_ylabel("signal")
    ax.legend(fontsize=8)

    ax = axes[2, 1]
    ax.plot(mastered_count_trace, linewidth=1.5, color="sienna")
    if agent.phase_1_end_step:
        ax.axvline(agent.phase_1_end_step, color="orange", linestyle="--")
    if agent.phase_2_end_step:
        ax.axvline(agent.phase_2_end_step, color="purple", linestyle="--")
    ax.set_title("Mastery accumulation")
    ax.set_xlabel("Step"); ax.set_ylabel("# pairs mastered")

    plt.tight_layout()
    plt.savefig("run_output_v0_8.png", dpi=110)

    # --- REPORT ---
    lines = []
    lines.append("=" * 72)
    lines.append("STRUCTURED CHARACTERISATION (v0.8 — 20x20 structured environment)")
    lines.append("=" * 72)
    lines.append(f"Life length              : {NUM_STEPS} steps")
    lines.append(f"Environment size         : {GRID_SIZE}x{GRID_SIZE}")
    lines.append(f"Passable cells in scope  : {len(world.scope_cells)}")
    lines.append(f"Hazard cells             : {len(world.hazard_cells)}")
    lines.append(f"Attractor cells          : {len(world.attractor_cells)}")
    lines.append("")
    lines.append("Phase 1 (Prescribed traversal):")
    lines.append(f"  Completed at step      : {agent.phase_1_end_step}")
    lines.append(f"  Cells covered          : {covered_at_phase_1_end}/{len(world.scope_cells)}")
    lines.append(f"  Path length            : {len(agent.prescribed_actions)} actions")
    lines.append("")
    if agent.phase_2_end_step:
        p2_duration = agent.phase_2_end_step - agent.phase_1_end_step
        lines.append(f"Phase 2 (Integration): {p2_duration} steps")
        lines.append(f"  Attractor visit ratio  : {attractor_ratio(heatmap_by_phase[2]):.2f}x chance")
        lines.append(f"  Attention CV           : {attention_cv(heatmap_by_phase[2]):.2f}")
        lines.append("")
    if agent.phase_2_end_step:
        p3_duration = NUM_STEPS - agent.phase_2_end_step
        lines.append(f"Phase 3 (Autonomy): {p3_duration} steps")
        lines.append(f"  Attractor visit ratio  : {attractor_ratio(heatmap_by_phase[3]):.2f}x chance")
        lines.append(f"  Attention CV           : {attention_cv(heatmap_by_phase[3]):.2f}")
        lines.append(f"  Attention concentration: {p3_concentration:.1f}x uniform")
        lines.append("")
    lines.append("RULE ADHERENCE (attempts to enter blocked cells):")
    lines.append(f"  Frame-directed  — P1: {agent.frame_attempts_by_phase[1]:4d}  "
                 f"P2: {agent.frame_attempts_by_phase[2]:4d}  "
                 f"P3: {agent.frame_attempts_by_phase[3]:4d}")
    lines.append(f"  Hazard-directed — P1: {agent.hazard_attempts_by_phase[1]:4d}  "
                 f"P2: {agent.hazard_attempts_by_phase[2]:4d}  "
                 f"P3: {agent.hazard_attempts_by_phase[3]:4d}")
    lines.append("")
    lines.append(f"Total pairs mastered       : {mastered_count_trace[-1]}")
    lines.append("")
    lines.append("Top 5 preferred cells at end of life:")
    for cell, pref in top_preferred:
        ctype = world.cell_type.get(cell, FRAME)
        marker = ""
        if ctype == ATTRACTOR:
            marker = " (ATTRACTOR)"
        elif any(abs(cell[0] - ax) + abs(cell[1] - ay) <= 1
                 for (ax, ay) in ATTRACTOR_CELLS):
            marker = " (near attractor)"
        lines.append(f"  {cell}: preference = {pref:.2f}{marker}")

    report_str = "\n".join(lines)
    print("\n" + report_str)
    with open("self_report_v0_8.txt", "w") as f:
        f.write(report_str)
    print("\nReport saved to self_report_v0_8.txt")
    print("Plots saved to run_output_v0_8.png")
    plt.show()


if __name__ == "__main__":
    run()
